import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadConfig } from '../packages/core/src/config.ts'
import { cli, copyFixture, sandbox } from './cli-helpers.ts'

const read = (root: string, p: string) => readFileSync(join(root, p), 'utf8')

function addSkill(root: string, name: string): void {
  mkdirSync(join(root, '.claude/skills', name), { recursive: true })
  writeFileSync(join(root, '.claude/skills', name, 'SKILL.md'), `---\nname: ${name}\ndescription: ${name} skill\n---\nBody of ${name}.\n`)
}

test('sync: .mdc → .claude/rules/cursor + cursor-* skills, profile → skillOverrides, DSL → prompt.generated.md + CLAUDE.md import', async () => {
  const root = copyFixture()
  addSkill(root, 'react-hooks')
  addSkill(root, 'nestjs')
  addSkill(root, 'tdd')
  writeFileSync(join(root, 'CLAUDE.md'), '# Project\n\nNotes.\n')
  writeFileSync(join(root, '.claude/settings.local.json'), JSON.stringify({ permissions: { allow: ['Bash(ls)'] } }))
  const r = await cli(root, ['sync', '--profile', 'backend', '--json'])
  assert.equal(r.code, 0, r.err)
  const res = JSON.parse(r.out)
  // always + auto → .claude/rules/cursor; agent-requested → skill.
  assert.match(read(root, '.claude/rules/cursor/always.md'), /Пиши тести поряд із кодом\./)
  assert.match(read(root, '.claude/rules/cursor/react.md'), /^---\npaths:\n {2}- "apps\/web\/\*\*\/\*\.tsx"\n---/)
  assert.match(read(root, '.claude/skills/cursor-api/SKILL.md'), /name: cursor-api\ndescription: "?Як проєктувати REST API"?/)
  assert.ok(!existsSync(join(root, '.claude/rules/cursor/api.md')))
  // backend profile: react-hooks is off, nestjs (backend) and tdd (tier core) stay on.
  const settings = JSON.parse(read(root, '.claude/settings.local.json'))
  assert.deepEqual(settings.permissions, { allow: ['Bash(ls)'] }, 'other settings kept')
  // Same values as hooks-adapter install (core skillOverridesFor): off → user-invocable-only unless --hard.
  assert.equal(settings.skillOverrides['react-hooks'], 'user-invocable-only')
  assert.equal(settings.skillOverrides.nestjs, undefined)
  assert.equal(settings.skillOverrides.tdd, undefined)
  assert.equal(res.overrides['react-hooks'], 'user-invocable-only')
  // One render of the DSL, imported from CLAUDE.md exactly once.
  const gen = read(root, '.claude/prompt.generated.md')
  assert.match(gen, /^<!-- generated by context-gate/)
  assert.match(gen, /Проєкт fixture-app\./)
  const md = read(root, 'CLAUDE.md')
  assert.match(md, /^# Project\n\nNotes\.\n\n@\.claude\/prompt\.generated\.md\n$/)
  // Idempotent: a second sync writes nothing.
  const again = JSON.parse((await cli(root, ['sync', '--profile', 'backend', '--json'])).out)
  assert.deepEqual(again.written, [])
  assert.equal(read(root, 'CLAUDE.md'), md)
  // Switching profile replaces our overrides; a removed rule's generated file is removed.
  writeFileSync(join(root, '.cursor/rules/react.mdc'), '---\ndescription: React now agent-requested\n---\nX\n')
  const fe = JSON.parse((await cli(root, ['sync', '--profile', 'frontend', '--hard', '--json'])).out)
  assert.ok(fe.removed.includes('.claude/rules/cursor/react.md'))
  assert.ok(existsSync(join(root, '.claude/skills/cursor-react/SKILL.md')))
  const s2 = JSON.parse(read(root, '.claude/settings.local.json'))
  assert.equal(s2.skillOverrides['react-hooks'], undefined)
  assert.equal(s2.skillOverrides.nestjs, 'off')
})

test('init: profiles guessed from apps/web, apps/api, packages/*, docs; classify shadow; .gitignore entries', async () => {
  const root = join(sandbox(), 'mono')
  for (const d of ['apps/web/src', 'apps/api/src', 'packages/ui', 'packages/db', 'docs']) mkdirSync(join(root, d), { recursive: true })
  writeFileSync(join(root, '.gitignore'), 'node_modules/\n')
  const r = await cli(root, ['init'])
  assert.equal(r.code, 0, r.err)
  const cfg = JSON.parse(read(root, '.claude/gate.json'))
  assert.deepEqual(Object.keys(cfg.profiles).sort(), ['backend', 'db', 'docs', 'frontend', 'ui'])
  assert.deepEqual(cfg.profiles.frontend.when.paths, ['apps/web/**'])
  assert.deepEqual(cfg.profiles.backend.when.paths, ['apps/api/**'])
  assert.deepEqual(cfg.profiles.ui.when.paths, ['packages/ui/**'])
  assert.deepEqual(cfg.profiles.docs.when.paths, ['docs/**', '**/*.md'])
  assert.equal(cfg.classify.mode, 'shadow')
  const v = loadConfig(read(root, '.claude/gate.json'))
  assert.ok(v.config, JSON.stringify(v.diagnostics))
  assert.equal(v.diagnostics.filter((d) => d.severity === 'error').length, 0)
  const gi = read(root, '.gitignore')
  assert.match(gi, /^node_modules\/\n/)
  assert.match(gi, /^\.claude\/prompt\/\.compiled\/$/m)
  assert.match(gi, /^\.claude\/gate\.log\.jsonl$/m)
  // Second init refuses without --force; .gitignore is not duplicated.
  assert.equal((await cli(root, ['init'])).code, 1)
  await cli(root, ['init', '--force'])
  assert.equal(read(root, '.gitignore').split('.claude/prompt/.compiled/').length, 2)
})

test('migrate: legacy skillGroups/mcpGroups → groups, with a backup; second run is a no-op', async () => {
  const root = join(sandbox(), 'legacy')
  mkdirSync(join(root, '.claude'), { recursive: true })
  const legacy = {
    skillGroups: { core: ['tdd'], frontend: ['react-*'] },
    mcpGroups: { frontend: ['figma'], always: ['github'] },
    tiers: { standard: { skills: ['core'] } },
    models: { '*sonnet*': 'standard' },
    profiles: { frontend: { skills: ['frontend'], mcp: ['frontend', 'always'], agents: ['ui-reviewer'] } },
    ruleSources: [{ kind: 'cursor-mdc', dir: '.cursor/rules' }],
  }
  writeFileSync(join(root, '.claude/gate.json'), JSON.stringify(legacy, null, 2))
  const dry = await cli(root, ['migrate', '--dry-run'])
  assert.equal(dry.code, 0)
  assert.equal(read(root, '.claude/gate.json'), JSON.stringify(legacy, null, 2), 'dry-run writes nothing')
  const r = await cli(root, ['migrate'])
  assert.equal(r.code, 0, r.err)
  assert.ok(existsSync(join(root, '.claude/gate.json.bak')))
  const cfg = JSON.parse(read(root, '.claude/gate.json'))
  assert.equal(cfg.skillGroups, undefined)
  assert.equal(cfg.mcpGroups, undefined)
  assert.equal(cfg.ruleSources, undefined)
  assert.deepEqual(cfg.groups.core, ['skill:tdd'])
  assert.deepEqual(cfg.groups.always, ['tool:mcp__github__*'])
  assert.deepEqual(cfg.itemSources, [{ kind: 'cursor-mdc', dir: '.cursor/rules' }])
  assert.ok(cfg.profiles.frontend.groups.includes('frontend-agents'))
  assert.equal(loadConfig(read(root, '.claude/gate.json')).diagnostics.filter((d) => d.code === 'G310').length, 0)
  const again = await cli(root, ['migrate'])
  assert.match(again.out, /уже в новому форматі/)
  assert.ok(!existsSync(join(root, '.claude/gate.json.bak.1')))
})
