// Generated by context-gate from .claude/gate.json; regenerated on build. Do not edit.
import type { GateCtx } from '@context-gate/jsx'

declare module '@context-gate/jsx' {
  interface CtxOverrides {
    gate: GateCtx<"frontend" | "backend" | "git" | "docs", "premium" | "standard" | "quick">
    eslint: unknown
    pkg: unknown
  }
}

export type ProfileName = "frontend" | "backend" | "git" | "docs"
export type TierName = "premium" | "standard" | "quick"
