// Markdown form of the prompt DSL: `@`-directives + `{{ expr }}` → the same AST as @context-gate/jsx
// (SPEC "Шар 3", "Шар 3а", Р5: canonical nodes only). Errors never stop parsing: a bad line gives a
// diagnostic and the parser moves on.

import type { Diagnostic, IncludeMode, Node, Scope, SectionNode, Tier } from './types.ts'
import { evalExpr, freeVars, isStatic, newBudget, parseExpr, splitTemplate } from './expr.ts'
import { canonicalNodes } from './canonical.ts'
import { parseDuration } from './duration.ts'

export interface MarkdownParseResult {
  section: SectionNode
  /** `use:` frontmatter map plus `@use` directives (namespace → path). */
  uses: Record<string, string>
  diagnostics: Diagnostic[]
  /** `source-hash` from frontmatter (tier variants generated by `expand`). */
  sourceHash?: string
  /** Raw frontmatter keys → values, for loaders. */
  frontmatter: Record<string, string | string[] | Record<string, string>>
}

export interface MarkdownParseOptions {
  path: string
  /** Section fields to inherit when frontmatter does not set them (tier variant files inherit the base). */
  inherit?: Partial<SectionNode>
  /**
   * Configured tier names. With them only `<id>.<tier>.md` of a known tier loses its suffix in the section id;
   * `release.notes.md` stays `release.notes`. Without them every `<a>.<b>.md` is read as a tier variant.
   */
  tiers?: Tier[]
}

const MAX_IF_DEPTH = 3
const MAX_LOOP_DEPTH = 2
const MAX_REPEAT = 1000
/** Nodes `@fn` expansion may produce per file (the interpreter's step limit): a chain of double calls is 2^N. */
const MAX_EXPANDED_NODES = 10_000

const DIRECTIVES = new Set([
  'if', 'elif', 'else', 'end', 'each', 'let', 'set', 'repeat', 'break', 'continue', 'store', 'run', 'call', 'use', 'include',
  'section', 'skill', 'rule', 'mcp', 'lazy', 'tier', 'fn', 'debug', 'assert', 'log', 'trace',
])

/** Parser-internal node: a call site of a local `@fn`, expanded in a post-pass. */
type FnCall = { t: 'fncall'; name: string; args: string[]; line: number }
type PNode = Node | FnCall

type Block =
  | { kind: 'root'; children: PNode[] }
  /** `chained`: opened by `@elif` / `@else if` inside the parent's else; closed by the same `@end`. */
  | { kind: 'if'; node: Extract<Node, { t: 'if' }>; then: PNode[]; else?: PNode[]; line: number; chained?: boolean }
  | { kind: 'each'; node: Extract<Node, { t: 'each' }>; children: PNode[]; line: number }
  | { kind: 'repeat'; node: Extract<Node, { t: 'repeat' }>; children: PNode[]; line: number }
  | { kind: 'tier'; node: Extract<Node, { t: 'tier' }>; children: PNode[]; line: number }
  | { kind: 'fn'; name: string; params: string[]; children: PNode[]; line: number; lets: Set<string> }

// ───────────────────────── small helpers ─────────────────────────

/** Split on `sep` outside quotes, parentheses and brackets. */
export function splitTopLevel(s: string, sep = ','): string[] {
  const out: string[] = []
  let depth = 0
  let quote = ''
  let cur = ''
  for (let i = 0; i < s.length; i++) {
    const c = s[i]
    if (quote) {
      cur += c
      if (c === '\\' && i + 1 < s.length) { cur += s[++i]; continue }
      if (c === quote) quote = ''
      continue
    }
    if (c === '"' || c === "'") { quote = c; cur += c; continue }
    if (c === '(' || c === '[' || c === '{') depth++
    if (c === ')' || c === ']' || c === '}') depth--
    if (depth === 0 && s.startsWith(sep, i)) { out.push(cur.trim()); cur = ''; i += sep.length - 1; continue }
    cur += c
  }
  if (cur.trim() || out.length) out.push(cur.trim())
  return out
}

/** Whitespace-separated words outside quotes; quotes are kept on the word. */
function words(s: string): string[] {
  return splitTopLevel(s.trim().replace(/\s+/g, ' '), ' ').filter(Boolean)
}

function unquote(s: string): string {
  const t = s.trim()
  if (t.length >= 2 && (t[0] === '"' || t[0] === "'") && t[t.length - 1] === t[0]) return t.slice(1, -1)
  return t
}

/** A quoted message (`@debug`, `@assert`, `@log`, descriptions): the quotes go, `\"` and `\\` lose the backslash. */
function unquoteMsg(s: string): string {
  const t = s.trim()
  return isQuoted(t) ? t.slice(1, -1).replace(/\\(["'\\])/g, '$1') : t
}

/** True when `s` is one string literal (no unescaped matching quote inside), e.g. `"a b"` but not `'a' in x || 'b'`. */
function isSingleLiteral(s: string): boolean {
  const t = s.trim()
  if (t.length < 2 || (t[0] !== '"' && t[0] !== "'") || t[t.length - 1] !== t[0]) return false
  for (let i = 1; i < t.length - 1; i++) {
    if (t[i] === '\\') { i++; continue }
    if (t[i] === t[0]) return false
  }
  return true
}

/** CommonMark fence opener/closer on a (trimmed) line: the run of ``` or ~~~ and the info string. */
function fenceLine(trimmed: string): { ch: string; len: number; info: string } | undefined {
  const m = /^(`{3,}|~{3,})(.*)$/.exec(trimmed)
  if (!m) return undefined
  // A backtick fence's info string cannot contain a backtick (``` `x` ``` is inline code).
  if (m[1][0] === '`' && m[2].includes('`')) return undefined
  return { ch: m[1][0], len: m[1].length, info: m[2].trim() }
}

const isQuoted = (s: string): boolean => /^(["']).*\1$/s.test(s.trim())

/** `name(arg, k=v) rest` → parts; undefined when parentheses are unbalanced. */
function splitCall(s: string): { name: string; args: string[]; kwargs: Record<string, string>; rest: string } | undefined {
  const m = /^([A-Za-z_][\w.-]*)\s*\(/.exec(s.trim())
  if (!m) return undefined
  const src = s.trim()
  let depth = 0
  let quote = ''
  let end = -1
  for (let i = m[0].length - 1; i < src.length; i++) {
    const c = src[i]
    if (quote) { if (c === '\\') { i++; continue } if (c === quote) quote = ''; continue }
    if (c === '"' || c === "'") { quote = c; continue }
    if (c === '(') depth++
    if (c === ')') { depth--; if (depth === 0) { end = i; break } }
  }
  if (end < 0) return undefined
  const inner = src.slice(m[0].length, end)
  const args: string[] = []
  const kwargs: Record<string, string> = {}
  for (const part of inner.trim() ? splitTopLevel(inner) : []) {
    const kw = /^([A-Za-z_][\w-]*)\s*=(?!=)\s*(.+)$/s.exec(part)
    if (kw) kwargs[kw[1]] = kw[2].trim()
    else args.push(part)
  }
  return { name: m[1], args, kwargs, rest: src.slice(end + 1).trim() }
}

/** `key=value` options and bare words. */
function options(ws: string[]): { bare: string[]; kv: Record<string, string> } {
  const bare: string[] = []
  const kv: Record<string, string> = {}
  for (const w of ws) {
    const m = /^([A-Za-z_][\w-]*)=(.*)$/s.exec(w)
    if (m) kv[m[1]] = unquote(m[2])
    else bare.push(w)
  }
  return { bare, kv }
}

const MODES = new Set(['inline', 'ref', 'lazy'])

// ───────────────────────── frontmatter ─────────────────────────

function parseFrontmatter(lines: string[], diags: Diagnostic[], path: string): { fm: MarkdownParseResult['frontmatter']; bodyStart: number } {
  const fm: MarkdownParseResult['frontmatter'] = {}
  if (lines[0]?.trim() !== '---') return { fm, bodyStart: 0 }
  let end = -1
  for (let i = 1; i < lines.length; i++) if (lines[i].trim() === '---') { end = i; break }
  if (end < 0) {
    diags.push({ code: 'G006', severity: 'error', message: 'Незакритий frontmatter (немає другого «---»)', path, line: 1 })
    return { fm, bodyStart: 0 }
  }
  let mapKey: string | undefined
  for (let i = 1; i < end; i++) {
    const raw = lines[i]
    if (!raw.trim() || raw.trim().startsWith('#')) continue
    const nested = /^\s+([\w.-]+)\s*:\s*(.*)$/.exec(raw)
    if (nested && mapKey) {
      const m = fm[mapKey] as Record<string, string>
      m[nested[1]] = unquote(nested[2])
      continue
    }
    const top = /^([\w.-]+)\s*:\s*(.*)$/.exec(raw)
    if (!top) {
      diags.push({ code: 'G006', severity: 'warning', message: `Незрозумілий рядок frontmatter: «${raw.trim()}»`, path, line: i + 1 })
      continue
    }
    const [, key, value] = top
    mapKey = undefined
    if (value === '') { fm[key] = {}; mapKey = key; continue }
    const v = value.trim()
    if (v.startsWith('[') && v.endsWith(']')) fm[key] = splitTopLevel(v.slice(1, -1)).map(unquote).filter(Boolean)
    // `when: 'a' in tags || mode == 'b'` is an expression: only a lone string literal loses its quotes.
    else fm[key] = isSingleLiteral(v) ? unquote(v) : v
  }
  return { fm, bodyStart: end + 1 }
}

function fmList(v: string | string[] | Record<string, string> | undefined): string[] | undefined {
  if (v === undefined) return undefined
  if (Array.isArray(v)) return v
  if (typeof v === 'string') return v.split(/[\s,]+/).filter(Boolean)
  return Object.keys(v)
}

/** `workflow.quick.md` → { id: 'workflow', tier: 'quick' }; plain `workflow.md` → undefined. */
export function tierVariantOf(path: string, tiers?: Tier[]): { id: string; tier: Tier } | undefined {
  const base = path.split('/').pop() ?? path
  const m = /^(.+)\.([\w-]+)\.md$/.exec(base)
  if (!m || m[2] === 'prompt') return undefined
  if (tiers && !tiers.includes(m[2])) return undefined
  return { id: m[1], tier: m[2] }
}

function idFromPath(path: string, tiers?: Tier[]): string {
  const base = (path.split('/').pop() ?? path).replace(/\.md$/, '')
  const v = tierVariantOf(path, tiers)
  return v ? v.id : base
}

// ───────────────────────── main parser ─────────────────────────

export function parseMarkdownPrompt(text: string, opts: MarkdownParseOptions): MarkdownParseResult {
  const path = opts.path
  const diagnostics: Diagnostic[] = []
  const lines = text.replace(/\r\n?/g, '\n').split('\n')
  const { fm, bodyStart } = parseFrontmatter(lines, diagnostics, path)
  const diag = (code: Diagnostic['code'], message: string, line: number, severity: Diagnostic['severity'] = 'error', hint?: string): void => {
    diagnostics.push({ code, severity, message, path, line, ...(hint ? { hint } : {}) })
  }
  // Р5: `store=` on @run/@call is the legacy form of `@store`; accepted until 1.0 with G180.
  const legacyStore = (d: 'run' | 'call', key: string, as: string | undefined, line: number): void => {
    diag('G180', `store= на @${d} — застаріла форма збереження`, line, 'warning', `@${d} … as=${as ?? key}, потім «@store ${as ?? key}${as && as !== key ? ` to=${key}` : ''}»`)
  }
  const checkExpr = (src: string, line: number): void => {
    for (const d of parseExpr(src).diagnostics) diagnostics.push({ ...d, path, line })
  }

  // Section meta.
  const inherit = opts.inherit ?? {}
  const scopeRaw = typeof fm.scope === 'string' ? fm.scope : undefined
  let scope: Scope = inherit.scope ?? 'profile'
  if (scopeRaw) {
    if (scopeRaw === 'static' || scopeRaw === 'profile' || scopeRaw === 'volatile') scope = scopeRaw
    else diag('G006', `Невідомий scope «${scopeRaw}» (static | profile | volatile)`, 1)
  }
  const section: SectionNode = { id: typeof fm.id === 'string' ? fm.id : inherit.id ?? idFromPath(path, opts.tiers), scope, children: [], source: { path, line: 1 } }
  const when = typeof fm.when === 'string' ? fm.when : inherit.when
  if (when) { section.when = when; checkExpr(when, 1) }
  if (fm.budget !== undefined) {
    const n = Number(fm.budget)
    if (Number.isFinite(n) && n > 0) section.budget = n
    else diag('G006', `budget має бути додатнім числом, отримано «${String(fm.budget)}»`, 1)
  } else if (inherit.budget !== undefined) section.budget = inherit.budget
  const after = typeof fm.after === 'string' ? fm.after : inherit.after
  if (after) section.after = after
  const tier = fmList(fm.tier) ?? inherit.tier
  if (tier && tier.length) section.tier = tier
  const uses: Record<string, string> = {}
  if (fm.use && typeof fm.use === 'object' && !Array.isArray(fm.use)) Object.assign(uses, fm.use)
  const sourceHash = typeof fm['source-hash'] === 'string' ? fm['source-hash'] : undefined

  const root: Block = { kind: 'root', children: [] }
  const stack: Block[] = [root]
  const fns = new Map<string, { params: string[]; body: PNode[]; line: number }>()
  const rootLets = new Set<string>()
  /** Open code fence (CommonMark: closed only by the same character, at least as long, without info). */
  let fence: { ch: string; len: number } | undefined
  let run: { node: Extract<Node, { t: 'run' }>; lines: string[]; line: number } | undefined

  const top = (): Block => stack[stack.length - 1]
  const target = (): PNode[] => {
    const b = top()
    if (b.kind === 'if') return b.else ?? b.then
    return b.children
  }
  const lets = (): Set<string> => {
    for (let i = stack.length - 1; i >= 0; i--) { const b = stack[i]; if (b.kind === 'fn') return b.lets }
    return rootLets
  }
  const depth = (kinds: Block['kind'][]): number => stack.filter(b => kinds.includes(b.kind) && !(b.kind === 'if' && b.chained)).length
  const pushText = (s: string, line: number): void => {
    const out = target()
    const lit = (text: string): void => {
      const last = out[out.length - 1]
      if (last && last.t === 'text') last.value += text
      else out.push({ t: 'text', value: text })
    }
    // `\{{` is a literal `{{` (GitHub Actions `$\{{ github.sha }}`, Helm, Jinja samples).
    const pieces = s.split('\\{{')
    pieces.forEach((piece, i) => {
      if (i) lit('{{')
      for (const part of splitTemplate(piece)) {
        if ('text' in part) { if (part.text) lit(part.text) } else {
          checkExpr(part.expr, line)
          out.push({ t: 'expr', expr: part.expr })
        }
      }
    })
  }

  for (let li = bodyStart; li < lines.length; li++) {
    const raw = lines[li]
    const line = li + 1
    const trimmed = raw.trim()

    if (run) {
      if (trimmed === '@end') {
        run.node.code = dedent(run.lines).join('\n').replace(/\n+$/, '')
        target().push(run.node)
        run = undefined
      } else run.lines.push(raw)
      continue
    }

    const fl = fenceLine(trimmed)
    if (fl && (!fence || (fl.ch === fence.ch && fl.len >= fence.len && !fl.info))) {
      fence = fence ? undefined : { ch: fl.ch, len: fl.len }
      pushText(raw + '\n', line)
      continue
    }
    if (fence || !trimmed.startsWith('@')) {
      pushText((trimmed.startsWith('\\@') ? raw.replace('\\@', '@') : raw) + '\n', line)
      continue
    }

    const dm = /^@([A-Za-z_][\w-]*)(.*)$/s.exec(trimmed)
    if (!dm) { pushText(raw + '\n', line); continue }
    const name = dm[1]
    const rest = dm[2].trim()

    if (!DIRECTIVES.has(name)) {
      if (dm[2].trimStart().startsWith('(')) {
        const c = splitCall(name + dm[2])
        if (!c || c.rest) { diag('G004', `Невірний виклик @${name}(…)`, line); continue }
        for (const a of c.args) checkExpr(a, line)
        target().push({ t: 'fncall', name, args: c.args, line })
        continue
      }
      diag('G001', `Невідома директива @${name} — рядок лишено як текст`, line, 'warning', 'екранувати як \\@')
      pushText(raw + '\n', line)
      continue
    }

    switch (name) {
      case 'if': {
        if (!rest) { diag('G004', '@if без умови', line); break }
        checkExpr(rest, line)
        if (depth(['if']) >= MAX_IF_DEPTH) diag('G156', `Вкладення @if глибше за ${MAX_IF_DEPTH}`, line, 'error', 'розбити секцію')
        const node: Extract<Node, { t: 'if' }> = { t: 'if', test: rest, then: [] }
        const b: Block = { kind: 'if', node, then: [], line }
        target().push(node)
        stack.push(b)
        break
      }
      case 'elif':
      case 'else': {
        const b = top()
        if (b.kind !== 'if' || b.else) { diag('G003', `@${name} без відповідного @if`, line); break }
        const elif = name === 'elif' ? rest : /^if\b/.test(rest) ? rest.slice(2).trim() : undefined
        if (elif === undefined) {
          if (rest) diag('G004', '@else не приймає аргументів (для умови — @else if / @elif)', line, 'warning')
          b.else = []
          break
        }
        if (!elif) { diag('G004', `@${name} без умови`, line); b.else = []; break }
        checkExpr(elif, line)
        const node: Extract<Node, { t: 'if' }> = { t: 'if', test: elif, then: [] }
        b.else = [node]
        stack.push({ kind: 'if', node, then: [], line, chained: true })
        break
      }
      case 'end': {
        const b = top()
        if (b.kind === 'root') { diag('G003', 'Зайвий @end', line); break }
        // One @end closes an @if together with all its @elif links.
        for (;;) {
          const x = top()
          closeBlock(x)
          stack.pop()
          if (!(x.kind === 'if' && x.chained)) break
        }
        break
      }
      case 'each': {
        const m = /^([A-Za-z_]\w*)(?:\s*,\s*([A-Za-z_]\w*))?\s+in\s+(.+)$/s.exec(rest)
        if (!m) { diag('G004', 'Очікувалось «@each x in <вираз>»', line); break }
        checkExpr(m[3], line)
        if (depth(['each', 'repeat']) >= MAX_LOOP_DEPTH) diag('G156', `Вкладення циклів глибше за ${MAX_LOOP_DEPTH}`, line, 'error', 'розбити секцію')
        const node: Extract<Node, { t: 'each' }> = { t: 'each', of: m[3].trim(), as: m[1], children: [] }
        if (m[2]) node.index = m[2]
        target().push(node)
        stack.push({ kind: 'each', node, children: [], line })
        break
      }
      case 'repeat': {
        if (!rest) { diag('G004', '@repeat без межі', line); break }
        checkExpr(rest, line)
        const p = parseExpr(rest)
        if (p.ast && isStatic(p.ast)) {
          let v: unknown = null
          try { v = evalExpr(p.ast, Object.create(null), newBudget()) } catch { v = null }
          if (typeof v !== 'number' || !Number.isFinite(v) || v > MAX_REPEAT || v < 0) diag('G152', `Межа @repeat має бути числом від 0 до ${MAX_REPEAT}, отримано ${JSON.stringify(v)}`, line, 'error', 'ця логіка має жити в провайдері')
        }
        if (depth(['each', 'repeat']) >= MAX_LOOP_DEPTH) diag('G156', `Вкладення циклів глибше за ${MAX_LOOP_DEPTH}`, line, 'error', 'розбити секцію')
        const node: Extract<Node, { t: 'repeat' }> = { t: 'repeat', n: rest, children: [] }
        target().push(node)
        stack.push({ kind: 'repeat', node, children: [], line })
        break
      }
      case 'let':
      case 'set': {
        const m = /^([A-Za-z_]\w*)\s*=(?!=)\s*(.+)$/s.exec(rest)
        if (!m) { diag('G004', `Очікувалось «@${name} ім'я = <вираз>»`, line); break }
        checkExpr(m[2], line)
        const L = lets()
        if (L.has(m[1])) diag('G153', `«${m[1]}» оголошено через @let — його не можна перевизначати`, line, 'error', '@let з новим іменем або @set')
        if (name === 'let') L.add(m[1])
        target().push({ t: name, name: m[1], value: m[2].trim() })
        break
      }
      case 'break':
      case 'continue': {
        // Inside @fn the call site decides (checked at expansion).
        const inLoop = stack.some(b => b.kind === 'each' || b.kind === 'repeat' || b.kind === 'fn')
        if (!inLoop) { diag('G005', `@${name} поза @each/@repeat`, line); break }
        target().push({ t: name })
        break
      }
      case 'store': {
        const sm = /^([A-Za-z_][\w-]*)(?:\s+to=([\w][\w.-]*))?$/.exec(rest)
        if (!sm) { diag('G004', 'Очікувалось «@store ім\'я [to=ключ]»', line); break }
        target().push({ t: 'store', name: sm[1]!, ...(sm[2] && sm[2] !== sm[1] ? { key: sm[2] } : {}) })
        break
      }
      case 'run': {
        const { bare, kv } = options(words(rest))
        const node: Extract<Node, { t: 'run' }> = { t: 'run', lang: bare[0] ?? 'bash', code: '' }
        if (bare.length > 1) diag('G004', `Зайві аргументи @run: ${bare.slice(1).join(' ')}`, line, 'warning')
        if (kv.as) node.as = kv.as
        if (kv.cache) node.cache = kv.cache
        if (kv.cache && parseDuration(kv.cache) === undefined) diag('G004', `cache=«${kv.cache}» — не тривалість (500ms, 10s, 5m, 1h, 1d, 1h30m)`, line, 'warning')
        if (kv.store) { node.store = kv.store; legacyStore('run', kv.store, node.as, line) }
        if (kv.needs) node.needs = kv.needs.split(',').map(s => s.trim()).filter(Boolean)
        if (!kv.cache && scope === 'static') diag('G163', '@run без cache у static-секції', line, 'error', 'додати cache=… або перенести у volatile')
        run = { node, lines: [], line }
        break
      }
      case 'call': {
        const c = splitCall(rest)
        if (!c || !c.name.includes('.')) { diag('G004', 'Очікувалось «@call ns.fn(args) as x»', line); break }
        const { bare, kv } = options(words(c.rest))
        if (bare[0] !== 'as' || !bare[1]) { diag('G004', '@call потребує «as <ім\'я>»', line); break }
        for (const a of [...c.args, ...Object.values(c.kwargs)]) checkExpr(a, line)
        const node: Extract<Node, { t: 'call' }> = { t: 'call', fn: c.name, args: c.args, as: bare[1] }
        if (Object.keys(c.kwargs).length) node.kwargs = c.kwargs
        if (kv.cache) node.cache = kv.cache
        if (kv.cache && parseDuration(kv.cache) === undefined) diag('G004', `cache=«${kv.cache}» — не тривалість (500ms, 10s, 5m, 1h, 1d, 1h30m)`, line, 'warning')
        if (kv.store) { node.store = kv.store; legacyStore('call', kv.store, node.as, line) }
        target().push(node)
        break
      }
      case 'use': {
        const ws = words(rest)
        if (ws.length !== 2) { diag('G004', 'Очікувалось «@use ім\'я шлях»', line); break }
        uses[ws[0]] = unquote(ws[1])
        target().push({ t: 'use', name: ws[0], path: unquote(ws[1]) })
        break
      }
      case 'include':
      case 'section':
      case 'skill':
      case 'rule': {
        const ws = words(rest)
        // The first word is the path / name even when quoted (`@include "docs/my notes.md"`); a quoted word
        // after it is the description.
        const first = ws[0] !== undefined && isQuoted(ws[0]) && !/^[A-Za-z_][\w-]*=/.test(ws[0]) ? [unquote(ws[0])] : []
        const restWs = first.length ? ws.slice(1) : ws
        const desc = restWs.filter(isQuoted).map(unquoteMsg)[0]
        const { bare: bareRest, kv } = options(restWs.filter(w => !isQuoted(w)))
        const bare = [...first, ...bareRest]
        if (!bare[0]) { diag('G004', `@${name} потребує ${name === 'include' ? 'шлях' : 'ім\'я'}`, line); break }
        const mode = (bare[1] ?? (name === 'include' || name === 'section' ? 'inline' : 'ref')) as IncludeMode
        if (!MODES.has(mode)) { diag('G004', `Невідомий режим «${mode}» (inline | ref | lazy)`, line); break }
        const ref = name === 'section' ? bare[0].replace(/^prompt:\/\//, '') : unquote(bare[0])
        const node: Extract<Node, { t: 'include' }> = { t: 'include', source: name === 'include' ? 'file' : name, ref, mode }
        if (kv.budget !== undefined) {
          const n = Number(kv.budget)
          if (Number.isFinite(n) && n > 0) node.budget = n
          else diag('G004', `budget має бути числом: «${kv.budget}»`, line)
        }
        if (desc) node.description = desc
        if (kv.as) node.as = kv.as
        target().push(node)
        break
      }
      case 'lazy': {
        const ws = words(rest)
        if (ws.length < 2) { diag('G004', 'Очікувалось «@lazy ім\'я шлях ["опис"]»', line); break }
        diag('G180', '@lazy — застаріла форма; використовуйте «@include <шлях> lazy»', line, 'warning')
        const node: Extract<Node, { t: 'include' }> = { t: 'include', source: 'file', ref: unquote(ws[1]), mode: 'lazy', as: ws[0] }
        const desc = ws.slice(2).map(unquote).join(' ')
        if (desc) node.description = desc
        target().push(node)
        break
      }
      case 'mcp': {
        const c = splitCall(rest)
        if (!c || !c.name.includes('.')) { diag('G004', 'Очікувалось «@mcp server.tool(k=v) as x»', line); break }
        if (c.args.length) diag('G004', '@mcp приймає лише іменовані аргументи k=v', line)
        for (const a of Object.values(c.kwargs)) checkExpr(a, line)
        const { bare } = options(words(c.rest))
        const node: Extract<Node, { t: 'include' }> = { t: 'include', source: 'mcp', ref: c.name, mode: 'inline', args: c.kwargs }
        if (bare[0] === 'as' && bare[1]) node.as = bare[1]
        else if (bare.length) diag('G004', `Зайве після @mcp: ${bare.join(' ')}`, line, 'warning')
        target().push(node)
        break
      }
      case 'tier': {
        const list = rest.split(/[\s,]+/).filter(Boolean)
        const node: Extract<Node, { t: 'tier' }> = { t: 'tier', is: list.length ? list : 'non-premium', children: [] }
        target().push(node)
        stack.push({ kind: 'tier', node, children: [], line })
        break
      }
      case 'fn': {
        const m = /^([A-Za-z_][\w-]*)\s*\(([^)]*)\)\s*$/.exec(rest)
        if (!m) { diag('G004', 'Очікувалось «@fn ім\'я(a, b)»', line); break }
        if (DIRECTIVES.has(m[1])) { diag('G004', `Ім'я @fn «${m[1]}» збігається з директивою`, line); break }
        const params = m[2].split(',').map(s => s.trim()).filter(Boolean)
        stack.push({ kind: 'fn', name: m[1], params, children: [], line, lets: new Set(params) })
        break
      }
      case 'debug': {
        const node: Extract<Node, { t: 'debug' }> = { t: 'debug', exprs: [] }
        const msg = /^("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')\s*(?!,)(.*)$/s.exec(rest)
        if (msg && (msg[2].includes('{{') || !msg[2].trim())) {
          node.message = unquoteMsg(msg[1]) + (msg[2].trim() ? ' ' + msg[2].trim() : '')
          for (const p of splitTemplate(node.message)) if ('expr' in p) checkExpr(p.expr, line)
        } else {
          node.exprs = splitTopLevel(rest).filter(Boolean)
          for (const e of node.exprs) checkExpr(e, line)
        }
        target().push(node)
        break
      }
      case 'assert': {
        const parts = splitTopLevel(rest)
        if (!parts[0]) { diag('G004', '@assert без умови', line); break }
        const node: Extract<Node, { t: 'assert' }> = { t: 'assert', test: parts[0] }
        if (parts.length > 1 && isQuoted(parts[parts.length - 1])) {
          node.message = unquoteMsg(parts[parts.length - 1])
          node.test = parts.slice(0, -1).join(', ')
        } else if (parts.length > 1) node.test = rest
        checkExpr(node.test, line)
        target().push(node)
        break
      }
      case 'log': {
        const ws = words(rest)
        const { bare, kv } = options(ws)
        const level = (kv.level ?? 'info') as 'info' | 'warn' | 'error'
        if (!['info', 'warn', 'error'].includes(level)) { diag('G004', `Невідомий level «${level}»`, line); break }
        target().push({ t: 'log', level, message: bare.map(unquoteMsg).join(' ') })
        break
      }
      case 'trace': {
        if (rest !== 'on' && rest !== 'off') { diag('G004', '@trace on | off', line); break }
        target().push({ t: 'trace', on: rest === 'on' })
        break
      }
    }
  }

  if (run) {
    diag('G002', '@run без @end — блок закрито в кінці файлу', run.line)
    run.node.code = dedent(run.lines).join('\n').replace(/\n+$/, '')
    target().push(run.node)
  }
  while (stack.length > 1) {
    const b = top()
    if (b.kind !== 'root' && !(b.kind === 'if' && b.chained)) diag('G002', `Незакритий блок @${b.kind} — закрито в кінці файлу`, b.line)
    closeBlock(b)
    stack.pop()
  }

  function closeBlock(b: Block): void {
    switch (b.kind) {
      case 'if': b.node.then = b.then as Node[]; if (b.else) b.node.else = b.else as Node[]; break
      case 'each':
      case 'repeat':
      case 'tier': b.node.children = b.children as Node[]; break
      case 'fn':
        if (fns.has(b.name)) diag('G004', `@fn «${b.name}» оголошено двічі`, b.line)
        fns.set(b.name, { params: b.params, body: b.children, line: b.line })
        break
    }
  }

  // `@fn`: static checks on the call graph first (unknown name G001, arity G004, recursion G151), then call
  // sites are inlined. Bodies are not expanded just to validate them, and the expanded size is bounded (G156).
  const seen = new Set<string>()
  const expDiag = (code: Diagnostic['code'], message: string, line: number): void => {
    const k = `${code}:${line}:${message}`
    if (seen.has(k)) return
    seen.add(k)
    diag(code, message, line, 'error', code === 'G151' ? 'ця логіка має жити в провайдері' : undefined)
  }
  const kids = (n: PNode): PNode[][] => n.t === 'if' ? [n.then as PNode[], (n.else ?? []) as PNode[]] : 'children' in n && Array.isArray(n.children) ? [n.children as PNode[]] : []
  const callsIn = (nodes: readonly PNode[], out: FnCall[] = []): FnCall[] => {
    for (const n of nodes) { if (n.t === 'fncall') out.push(n); else for (const k of kids(n)) callsIn(k, out) }
    return out
  }
  for (const c of [...callsIn(root.children), ...[...fns.values()].flatMap(f => callsIn(f.body))]) {
    const fn = fns.get(c.name)
    if (!fn) expDiag('G001', `Невідома директива або функція @${c.name}`, c.line)
    else if (c.args.length !== fn.params.length) expDiag('G004', `@${c.name} очікує ${fn.params.length} аргумент(и), отримано ${c.args.length}`, c.line)
  }
  const recursive = new Set<string>()
  {
    const state = new Map<string, 1 | 2>()
    const cycles = new Set<string>()
    const dfs = (name: string, path: string[]): void => {
      state.set(name, 1)
      for (const c of callsIn(fns.get(name)!.body)) {
        if (!fns.has(c.name)) continue
        const st = state.get(c.name)
        if (st === 1) {
          const cycle = path.slice(path.indexOf(c.name))
          cycle.forEach(x => recursive.add(x))
          const k = [...cycle].sort().join(',')
          if (!cycles.has(k)) { cycles.add(k); expDiag('G151', `Рекурсія @fn: ${[...cycle, c.name].join(' → ')}`, c.line) }
        } else if (!st) dfs(c.name, [...path, c.name])
      }
      state.set(name, 2)
    }
    for (const name of fns.keys()) if (!state.has(name)) dfs(name, [name])
  }
  // Expanded node count of one call (memoized; recursion already reported counts as 0).
  const sizes = new Map<string, number>()
  const sizeOfNodes = (nodes: readonly PNode[]): number => {
    let total = 0
    for (const n of nodes) {
      if (n.t === 'fncall') { const fn = fns.get(n.name); total += 1 + (fn ? 2 * fn.params.length + sizeOfFn(n.name) : 0) } else {
        total++
        for (const k of kids(n)) total += sizeOfNodes(k)
      }
      if (total > MAX_EXPANDED_NODES) return total
    }
    return total
  }
  const sizeOfFn = (name: string): number => {
    if (recursive.has(name)) return 0
    const memo = sizes.get(name)
    if (memo !== undefined) return memo
    sizes.set(name, 0)
    const n = Math.min(sizeOfNodes(fns.get(name)!.body), MAX_EXPANDED_NODES + 1)
    sizes.set(name, n)
    return n
  }
  // `@break` / `@continue` that leave the body outside any loop of the body (memoized per fn).
  const escapes = new Map<string, boolean>()
  const escapesNodes = (nodes: readonly PNode[]): boolean => nodes.some(n =>
    n.t === 'break' || n.t === 'continue' ? true
      : n.t === 'fncall' ? escapesFn(n.name)
        : n.t === 'each' || n.t === 'repeat' ? false
          : kids(n).some(escapesNodes))
  const escapesFn = (name: string): boolean => {
    if (!fns.has(name) || recursive.has(name)) return false
    if (!escapes.has(name)) { escapes.set(name, false); escapes.set(name, escapesNodes(fns.get(name)!.body)) }
    return escapes.get(name)!
  }
  let expanded = 0
  let tooBig = false
  let tmp = 0
  const expand = (nodes: PNode[], chain: string[], inLoop: boolean): Node[] => {
    const out: Node[] = []
    for (const n of nodes) {
      if (n.t === 'fncall') {
        const fn = fns.get(n.name)
        if (!fn || recursive.has(n.name) || chain.includes(n.name)) continue
        if (!chain.length) {
          expanded += sizeOfFn(n.name)
          if (expanded > MAX_EXPANDED_NODES) {
            if (!tooBig) { tooBig = true; expDiag('G156', `Розгортання @fn дає понад ${MAX_EXPANDED_NODES} вузлів (виклик @${n.name})`, n.line) }
            continue
          }
        }
        if (!inLoop && escapesFn(n.name)) expDiag('G005', `@break/@continue у @${n.name} поза @each/@repeat`, n.line)
        // Arguments are evaluated in the caller's frame: when one names an earlier parameter (`@pair(b, a)`),
        // bind every argument to a temporary first, then the parameters.
        const params = fn.params
        const args = params.map((_, i) => n.args[i] ?? 'null')
        const clash = args.some((a, i) => { const p = parseExpr(a); return !!p.ast && freeVars(p.ast).some(v => params.indexOf(v) >= 0 && params.indexOf(v) < i) })
        let binds: Node[]
        if (clash) {
          const id = tmp++
          binds = [
            ...args.map((a, i): Node => ({ t: 'let', name: `__fn${id}_${i}`, value: a })),
            ...params.map((p, i): Node => ({ t: 'let', name: p, value: `__fn${id}_${i}` })),
          ]
        } else binds = params.map((p, i): Node => ({ t: 'let', name: p, value: args[i] }))
        out.push({ t: 'if', test: 'true', then: [...binds, ...expand(fn.body, [...chain, n.name], inLoop)] })
        continue
      }
      out.push(expandChildren(n, chain, inLoop))
    }
    return out
  }
  const expandChildren = (n: Node, chain: string[], inLoop: boolean): Node => {
    switch (n.t) {
      case 'if': return { ...n, then: expand(n.then, chain, inLoop), ...(n.else ? { else: expand(n.else, chain, inLoop) } : {}) }
      case 'each':
      case 'repeat': return { ...n, children: expand(n.children, chain, true) } as Node
      case 'tier':
      case 'el':
      case 'fence':
      case 'list': return { ...n, children: expand(n.children, chain, inLoop) } as Node
      default: return n
    }
  }
  // Frontmatter `use:` bindings become canonical `use` nodes at the top of the section.
  const fmUses: Node[] = fm.use && typeof fm.use === 'object' && !Array.isArray(fm.use)
    ? Object.entries(fm.use).map(([name, p]) => ({ t: 'use', name, path: p }))
    : []
  // Р5: only canonical nodes leave the compiler (`store=` → `store`, `@let x = scripts.f()` → `call`).
  section.children = canonicalNodes([...fmUses, ...expand(root.children, [], false)])

  return { section, uses, diagnostics, ...(sourceHash ? { sourceHash } : {}), frontmatter: fm }
}

function dedent(lines: string[]): string[] {
  let ind = Infinity
  for (const l of lines) if (l.trim()) ind = Math.min(ind, /^[ \t]*/.exec(l)![0].length)
  if (!Number.isFinite(ind) || ind === 0) return lines
  return lines.map(l => l.slice(Math.min(ind, /^[ \t]*/.exec(l)![0].length)))
}

/** A `<id>.<tier>.md` variant overrides the canonical section fully for that tier (SPEC Шар 3а). */
export function resolveTierVariant(base: SectionNode, variants: Record<Tier, SectionNode>, tier: Tier): SectionNode {
  const v = Object.prototype.hasOwnProperty.call(variants, tier) ? variants[tier] : undefined
  if (!v) return base
  const out: SectionNode = { ...v, id: base.id }
  // A variant file is already the variant for this tier: a `tier` filter inherited from the base must not drop it.
  delete out.tier
  return out
}

// ───────────────────────── AST → Markdown form ─────────────────────────

/**
 * Prints AST nodes back in the Markdown DSL form (`@if`, `@each`, `{{ }}` …). Used by `expand` to show a
 * TSX section to the model as canonical text (SPEC «Шар 3а»), and by tooling that wants a readable view
 * of a compiled section. The output parses back into an equivalent section (`parseMarkdownPrompt`).
 */
export function printMarkdownNodes(nodes: readonly Node[]): string {
  let out = ''
  const nl = (): void => { if (out && !out.endsWith('\n')) out += '\n' }
  const dir = (line: string): void => { nl(); out += line + '\n' }
  // A text `@` is escaped only where it starts a physical line of the output (the parser unescapes `\@` only
  // there); it is marked here and resolved once the whole text is known. `{{` in text is always literal.
  const text = (s: string): void => { out += s.replace(/@/g, AT_MARK).replace(/\{\{/g, '\\{{') }
  const fence = (body: string): string => {
    let max = 0
    for (const m of body.matchAll(/`+/g)) max = Math.max(max, m[0].length)
    return '`'.repeat(Math.max(3, max + 1))
  }
  const q = (s: string): string => JSON.stringify(s)
  const opts = (kv: Record<string, string | undefined>): string => Object.entries(kv).filter(([, v]) => v !== undefined && v !== '').map(([k, v]) => ` ${k}=${/\s/.test(v!) ? q(v!) : v}`).join('')
  const inline = (list: readonly Node[]): string => { const save = out; out = ''; walk(list, undefined); const r = out; out = save; return r }
  const walk = (list: readonly Node[], listKind: 'ol' | 'ul' | undefined): void => {
    for (const n of list) {
      switch (n.t) {
        case 'text': text(n.value); break
        case 'expr': out += `{{ ${n.expr} }}`; break
        case 'el': {
          const inner = (): string => inline(n.children)
          switch (n.tag) {
            case 'li': nl(); out += (listKind === 'ol' ? '1. ' : '- ') + inner().trim() + '\n'; break
            case 'ol': case 'ul': nl(); walk(n.children.filter((c) => !(c.t === 'text' && !c.value.trim())), n.tag); break
            case 'code': out += '`' + inner() + '`'; break
            case 'pre': { nl(); const body = inner().replace(/^\n+|\n+$/g, ''); const f = fence(body); out += f + (n.attrs?.lang ?? '') + '\n' + body + '\n' + f + '\n'; break }
            case 'b': out += `**${inner()}**`; break
            case 'i': out += `*${inner()}*`; break
            case 'p': nl(); out += inner().trim() + '\n\n'; break
            case 'br': out += '\n'; break
            default: {
              const h = /^h([1-6])$/.exec(n.tag)
              if (h) { nl(); out += '#'.repeat(Number(h[1])) + ' ' + inner().trim() + '\n' } else out += inner()
            }
          }
          break
        }
        case 'if': {
          dir(`@if ${n.test}`)
          walk(n.then, listKind)
          // An else that is a single `if` is what `@elif` parses into: print the chain flat (one @end, no depth).
          let rest = n.else
          while (rest && rest.length === 1 && rest[0].t === 'if') {
            const x: Extract<Node, { t: 'if' }> = rest[0]
            dir(`@elif ${x.test}`)
            walk(x.then, listKind)
            rest = x.else
          }
          if (rest?.length) { dir('@else'); walk(rest, listKind) }
          dir('@end')
          break
        }
        case 'each': dir(`@each ${n.as}${n.index ? `, ${n.index}` : ''} in ${n.of}`); walk(n.children, listKind); dir('@end'); break
        case 'let': case 'set': dir(`@${n.t} ${n.name} = ${n.value}`); break
        case 'repeat': dir(`@repeat ${n.n}`); walk(n.children, listKind); dir('@end'); break
        case 'break': case 'continue': dir(`@${n.t}`); break
        case 'store': dir(`@store ${n.name}${n.key ? ` to=${n.key}` : ''}`); break
        case 'run': dir(`@run ${n.lang}${opts({ as: n.as, cache: n.cache, store: n.store, needs: n.needs?.join(',') })}`); out += n.code + '\n'; dir('@end'); break
        case 'use': dir(`@use ${n.name} ${n.path}`); break
        case 'call': {
          const args = [...n.args, ...Object.entries(n.kwargs ?? {}).map(([k, v]) => `${k}=${v}`)].join(', ')
          dir(`@call ${n.fn}(${args}) as ${n.as}${opts({ cache: n.cache, store: n.store })}`)
          break
        }
        case 'include': {
          if (n.source === 'text') { text(n.text ?? ''); break }
          if (n.source === 'mcp') { dir(`@mcp ${n.ref}(${Object.entries(n.args ?? {}).map(([k, v]) => `${k}=${v}`).join(', ')})${n.as ? ` as ${n.as}` : ''}`); break }
          const d = n.source === 'file' ? 'include' : n.source
          dir(`@${d} ${n.source === 'section' ? `prompt://${n.ref}` : n.ref} ${n.mode}${opts({ budget: n.budget === undefined ? undefined : String(n.budget), as: n.source === 'file' ? n.as : undefined })}${n.description ? ` ${q(n.description)}` : ''}`)
          break
        }
        case 'tier': dir(`@tier${n.is === 'non-premium' ? '' : ' ' + n.is.join(', ')}`); walk(n.children, listKind); dir('@end'); break
        case 'fence': { nl(); const body = inline(n.children).replace(/^\n+|\n+$/g, ''); const f = fence(body); out += f + (n.lang ?? '') + (n.title ? ` ${n.title}` : '') + '\n' + body + '\n' + f + '\n'; break }
        case 'list': walk(n.children, n.ordered ? 'ol' : 'ul'); break
        case 'table': {
          nl()
          out += `| ${n.columns.join(' | ')} |\n|${n.columns.map(() => ' --- |').join('')}\n`
          dir(`@each row in ${n.rows}`)
          out += `| ${n.cells.map((c) => `{{ ${c} }}`).join(' | ')} |\n`
          dir('@end')
          break
        }
        case 'debug': dir(`@debug ${n.message ? q(n.message) + (n.exprs.length ? ' ' : '') : ''}${n.exprs.join(', ')}`); break
        case 'assert': dir(`@assert ${n.test}${n.message ? `, ${q(n.message)}` : ''}`); break
        case 'log': dir(`@log level=${n.level} ${q(n.message)}`); break
        case 'trace': dir(`@trace ${n.on ? 'on' : 'off'}`); break
      }
    }
  }
  walk(nodes, undefined)
  const lines = out.replace(/\n{3,}/g, '\n\n').trim().split('\n')
  return lines.map(l => l.replace(new RegExp(`^([ \\t]*)${AT_MARK}`), '$1\\@').split(AT_MARK).join('@')).join('\n')
}

/** Private-use placeholder for a text `@` while printing (see `printMarkdownNodes`). */
const AT_MARK = '\uE000'

/** True when the nodes already carry tier variants (`tier` nodes anywhere). */
export function hasTierNodes(nodes: readonly Node[]): boolean {
  for (const n of nodes) {
    if (n.t === 'tier') return true
    if (n.t === 'if' && (hasTierNodes(n.then) || hasTierNodes(n.else ?? []))) return true
    if ('children' in n && Array.isArray(n.children) && hasTierNodes(n.children)) return true
  }
  return false
}
