// Generated by context-gate: ambient types for text imports in prompts.
declare module '*.md' {
  const text: string
  export default text
  export const meta: Record<string, unknown>
}
declare module '*.mdc' {
  const text: string
  export default text
  export const meta: Record<string, unknown>
}
declare module '*.txt' {
  const text: string
  export default text
  export const meta: Record<string, unknown>
}
