// Generated by context-gate from .claude/gate.json; regenerated on build. Do not edit.
import type { GateCtx } from '@context-gate/jsx'

declare module '@context-gate/jsx' {
  interface CtxOverrides {
    gate: GateCtx<"docs" | "planning" | "release" | "agents-md", "premium" | "standard" | "quick">
    ci: unknown
    pkg: {
      name?: string
      version?: string
      scripts?: {
        [key: string]: unknown
      }
    }
  }
}

export type ProfileName = "docs" | "planning" | "release" | "agents-md"
export type TierName = "premium" | "standard" | "quick"
