// `context-gate sync`: the static harness adapter (SPEC «Режими запуску», сценарій 9). Without mods:
//   .mdc → .claude/rules/cursor/*.md (always/auto) + .claude/skills/cursor-<id>/SKILL.md (agent/manual)
//   profile/tier decision → skillOverrides in .claude/settings.local.json
//   DSL → one render into .claude/prompt.generated.md, imported from CLAUDE.md with `@.claude/prompt.generated.md`

import { existsSync, readdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { skillNameForRule, transpileAgentRule, transpileRuleToClaudeRule } from '../../core/src/mdc.ts'
import { buildContext, type ContextOptions } from './context.ts'
import { renderWith } from './cmd-run.ts'
import { posix, readJson, readText, walkFiles, writeJson, writeText } from './util.ts'

export const GENERATED_PROMPT = '.claude/prompt.generated.md'
export const IMPORT_LINE = '@.claude/prompt.generated.md'
const MARK = 'generated by context-gate'

export interface SyncResult { written: string[]; removed: string[]; unchanged: number; overrides: Record<string, string> }

function writeIfChanged(root: string, rel: string, text: string, res: SyncResult): void {
  const abs = join(root, rel)
  if (readText(abs) === text) { res.unchanged++; return }
  writeText(abs, text)
  res.written.push(rel)
}

export async function syncCommand(o: ContextOptions & { noPrompt?: boolean; noRules?: boolean; noOverrides?: boolean }): Promise<SyncResult> {
  const ctx = await buildContext({ ...o, dryScripts: o.dryScripts })
  const root = ctx.repo.root
  const res: SyncResult = { written: [], removed: [], unchanged: 0, overrides: {} }

  // ── rules ──
  if (!o.noRules) {
    const wantRules = new Set<string>()
    const wantSkills = new Set<string>()
    for (const r of ctx.rules) {
      const md = transpileRuleToClaudeRule(r)
      if (md !== undefined) {
        const rel = `.claude/rules/cursor/${r.id}.md`
        wantRules.add(rel)
        writeIfChanged(root, rel, md, res)
      } else {
        const name = skillNameForRule(r)
        const rel = `.claude/skills/${name}/SKILL.md`
        wantSkills.add(name)
        writeIfChanged(root, rel, transpileAgentRule(r), res)
      }
    }
    // Remove generated files whose rule disappeared.
    for (const f of existsSync(join(root, '.claude/rules/cursor')) ? walkFiles(root, { under: '.claude/rules/cursor' }) : []) {
      if (f.endsWith('.md') && !wantRules.has(f) && (readText(join(root, f)) ?? '').includes(MARK)) { rmSync(join(root, f)); res.removed.push(f) }
    }
    const skillsDir = join(root, '.claude/skills')
    if (existsSync(skillsDir)) {
      for (const d of readdirSync(skillsDir)) {
        if (!d.startsWith('cursor-') || wantSkills.has(d)) continue
        const p = join(skillsDir, d, 'SKILL.md')
        if ((readText(p) ?? '').includes(MARK)) { rmSync(join(skillsDir, d), { recursive: true, force: true }); res.removed.push(`.claude/skills/${d}/SKILL.md`) }
      }
    }
  }

  // ── skillOverrides for the chosen profile / tier ──
  if (!o.noOverrides) {
    const gate = ctx.gate
    const overrides: Record<string, string> = {}
    for (const id of gate.skills.off) overrides[id.replace(/^skill:/, '')] = 'off'
    for (const id of gate.skills.nameOnly) overrides[id.replace(/^skill:/, '')] = 'name-only'
    res.overrides = overrides
    const settingsRel = '.claude/settings.local.json'
    const statePath = join(ctx.repo.cacheDir, 'sync-state.json')
    const state = readJson<{ overrides?: string[] }>(statePath) ?? {}
    const settings = readJson<Record<string, unknown>>(join(root, settingsRel)) ?? {}
    const cur = (settings.skillOverrides && typeof settings.skillOverrides === 'object' ? { ...(settings.skillOverrides as Record<string, string>) } : {})
    for (const k of state.overrides ?? []) delete cur[k]
    const next = { ...cur, ...overrides }
    const out = { ...settings }
    if (Object.keys(next).length) out.skillOverrides = Object.fromEntries(Object.entries(next).sort(([a], [b]) => a.localeCompare(b)))
    else delete out.skillOverrides
    if (JSON.stringify(out) !== JSON.stringify(settings) || !existsSync(join(root, settingsRel)) && Object.keys(next).length) {
      writeJson(join(root, settingsRel), out)
      res.written.push(settingsRel)
    } else res.unchanged++
    writeJson(statePath, { overrides: Object.keys(overrides) })
  }

  // ── DSL → one render + CLAUDE.md import ──
  if (!o.noPrompt && (ctx.prompts.system.length > 0)) {
    const r = await renderWith(ctx, {})
    const head = `<!-- ${MARK}: context-gate sync (tier ${ctx.tier}${ctx.gate.profile ? `, профіль ${ctx.gate.profile}` : ''}); не редагуй вручну, джерело — ${ctx.repo.promptDir} -->`
    writeIfChanged(root, GENERATED_PROMPT, `${head}\n\n${r.result.text}\n`, res)
    const claudeMd = join(root, 'CLAUDE.md')
    const cur = readText(claudeMd)
    if (cur === undefined) writeIfChanged(root, 'CLAUDE.md', `${IMPORT_LINE}\n`, res)
    else if (!cur.split('\n').some((l) => l.trim() === IMPORT_LINE)) writeIfChanged(root, 'CLAUDE.md', cur + (cur.endsWith('\n') || !cur ? '' : '\n') + `\n${IMPORT_LINE}\n`, res)
    else res.unchanged++
  }
  return res
}

export function syncWatchPaths(root: string, promptDir: string): string[] {
  return ['.cursor/rules', promptDir, '.claude/gate.json'].map((p) => join(root, p)).filter((p) => existsSync(p) || existsSync(dirname(p)))
}

export function formatSync(res: SyncResult): string {
  const lines: string[] = []
  for (const w of res.written) lines.push(`записано ${posix(w)}`)
  for (const r of res.removed) lines.push(`видалено ${posix(r)}`)
  lines.push(`без змін: ${res.unchanged}; skillOverrides: ${Object.keys(res.overrides).length}`)
  return lines.join('\n') + '\n'
}
