// `context-gate sync`: the static harness adapter (SPEC «Режими запуску», сценарій 9). Without mods:
//   .mdc → .claude/rules/cursor/*.md (always/auto) + .claude/skills/cursor-<id>/SKILL.md (agent/manual)
//   profile/tier decision → skillOverrides in .claude/settings.local.json
//   DSL → one render into .claude/prompt.generated.md, imported from CLAUDE.md with `@.claude/prompt.generated.md`
//   --agents-md AGENTS.md,…: only that — the render without volatile sections, between markers in files other agent CLIs read

import { existsSync, readdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { Diagnostic } from '../../core/src/types.ts'
import { cursorRuleDirs, ruleSourcesOf, skillNameForRule, transpileAgentRule, transpileRuleToClaudeRule } from '../../core/src/mdc.ts'
import { skillOverridesFor } from '../../core/src/decide.ts'
import { buildContext, loadRepo, type ContextOptions } from './context.ts'
import { ensureBuilt, renderWith } from './cmd-run.ts'
import { posix, readJson, readText, repoPathInside, walkFiles, writeJson, writeText } from './util.ts'

export const GENERATED_PROMPT = '.claude/prompt.generated.md'
export const IMPORT_LINE = '@.claude/prompt.generated.md'
const MARK = 'generated by context-gate'

export interface SyncResult {
  written: string[]
  removed: string[]
  unchanged: number
  overrides: Record<string, string>
  /** H013 (stale TSX, not rebuilt), build errors, a settings file that does not parse, shadow-mode notes. */
  diagnostics?: Diagnostic[]
}

/**
 * Reads a JSON settings file for a read-modify-write: `{}` when it does not exist, `undefined` when it exists but
 * does not parse (a trailing comma by hand) — the caller must then refuse to write, or the user's other settings
 * (permissions, hooks) would be lost.
 */
export function readSettingsForUpdate(abs: string): Record<string, unknown> | undefined {
  const text = readText(abs)
  if (text === undefined) return {}
  const v = readJson<unknown>(abs)
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : undefined
}

function writeIfChanged(root: string, rel: string, text: string, res: SyncResult): void {
  const abs = join(root, rel)
  // The repo controls its links: a path through a directory link out of it is refused (Р2), not followed.
  if (!repoPathInside(root, abs)) { res.diagnostics!.push(escapeDiag(rel)); return }
  if (readText(abs) === text) { res.unchanged++; return }
  writeText(abs, text, root)
  res.written.push(rel)
}

function escapeDiag(rel: string): Diagnostic {
  return { code: 'G314', severity: 'warning', message: `${rel}: шлях веде за межі репозиторію (symlink) — не записано`, path: rel }
}

export async function syncCommand(o: ContextOptions & { noPrompt?: boolean; noRules?: boolean; noOverrides?: boolean; hard?: boolean; agentsMd?: string[] }): Promise<SyncResult> {
  let ctx = await buildContext({ ...o, dryScripts: o.dryScripts })
  const root = ctx.repo.root
  const res: SyncResult = { written: [], removed: [], unchanged: 0, overrides: {}, diagnostics: [] }
  // The static adapter is the only path of the DSL to the model: a stale .compiled is rebuilt when allowed (as
  // `run` does), else reported (H013) instead of silently rendering the old text into prompt.generated.md.
  if (!o.noPrompt) {
    const built = await ensureBuilt(root, ctx.repo.promptDir, ctx.host.trusted, ctx.repo.config.prompt?.build)
    res.diagnostics!.push(...built.diagnostics)
    if (built.built || built.diagnostics.length) ctx = await buildContext({ ...o, dryScripts: o.dryScripts })
  }

  // `--agents-md` writes only those files: in a repo with the plugin, prompt.generated.md and skillOverrides would
  // give Claude Code the same sections twice.
  if (o.agentsMd?.length) {
    if (ctx.prompts.system.length > 0) await writeAgentsMd(ctx, o.agentsMd, res)
    return res
  }

  // ── rules ──
  if (!o.noRules) {
    const wantRules = new Set<string>()
    const wantSkills = new Set<string>()
    for (const r of ctx.rules) {
      const md = transpileRuleToClaudeRule(r)
      if (md !== undefined) {
        const rel = `.claude/rules/cursor/${r.id}.md`
        wantRules.add(rel)
        writeIfChanged(root, rel, md, res)
      } else {
        const name = skillNameForRule(r)
        const rel = `.claude/skills/${name}/SKILL.md`
        wantSkills.add(name)
        writeIfChanged(root, rel, transpileAgentRule(r), res)
      }
    }
    // Remove generated files whose rule disappeared.
    for (const f of existsSync(join(root, '.claude/rules/cursor')) ? walkFiles(root, { under: '.claude/rules/cursor' }) : []) {
      if (f.endsWith('.md') && !wantRules.has(f) && (readText(join(root, f)) ?? '').includes(MARK)) { rmSync(join(root, f)); res.removed.push(f) }
    }
    const skillsDir = join(root, '.claude/skills')
    if (existsSync(skillsDir)) {
      for (const d of readdirSync(skillsDir)) {
        if (!d.startsWith('cursor-') || wantSkills.has(d)) continue
        const p = join(skillsDir, d, 'SKILL.md')
        if ((readText(p) ?? '').includes(MARK)) { rmSync(join(skillsDir, d), { recursive: true, force: true }); res.removed.push(`.claude/skills/${d}/SKILL.md`) }
      }
    }
  }

  // ── skillOverrides for the chosen profile / tier ──
  if (!o.noOverrides) {
    const gate = ctx.gate
    // classify.mode: shadow promises that nothing is filtered: without an explicit --profile/--tier sync hides no
    // skill (it still removes the overrides it wrote before).
    const shadow = ctx.repo.config.classify?.mode === 'shadow' && !o.profile && !o.tier
    const overrides: Record<string, string> = shadow ? {} : skillOverridesFor(gate, { hard: !!o.hard })
    res.overrides = overrides
    const settingsRel = '.claude/settings.local.json'
    const statePath = join(ctx.repo.cacheDir, 'sync-state.json')
    const state = readJson<{ overrides?: string[] }>(statePath) ?? {}
    const settings = readSettingsForUpdate(join(root, settingsRel))
    if (!settings) {
      res.diagnostics!.push({ code: 'G301', severity: 'warning', message: `${settingsRel} не парситься як JSON-об'єкт — skillOverrides не записано, файл не змінено`, path: settingsRel, hint: 'виправ JSON (кома в кінці?) і запусти sync знову' })
    } else {
      const cur = (settings.skillOverrides && typeof settings.skillOverrides === 'object' ? { ...(settings.skillOverrides as Record<string, string>) } : {})
      for (const k of state.overrides ?? []) delete cur[k]
      const next = { ...cur, ...overrides }
      const out = { ...settings }
      if (Object.keys(next).length) out.skillOverrides = Object.fromEntries(Object.entries(next).sort(([a], [b]) => a.localeCompare(b)))
      else delete out.skillOverrides
      if (!repoPathInside(root, join(root, settingsRel))) res.diagnostics!.push(escapeDiag(settingsRel))
      else if (JSON.stringify(out) !== JSON.stringify(settings) || !existsSync(join(root, settingsRel)) && Object.keys(next).length) {
        writeJson(join(root, settingsRel), out, root)
        res.written.push(settingsRel)
      } else res.unchanged++
      writeJson(statePath, { overrides: Object.keys(overrides) })
    }
  }

  // ── DSL → one render + CLAUDE.md import ──
  if (!o.noPrompt && (ctx.prompts.system.length > 0)) {
    const r = await renderWith(ctx, {})
    const head = `<!-- ${MARK}: context-gate sync (tier ${ctx.tier}${ctx.gate.profile ? `, профіль ${ctx.gate.profile}` : ''}); не редагуй вручну, джерело — ${ctx.repo.promptDir} -->`
    writeIfChanged(root, GENERATED_PROMPT, `${head}\n\n${r.result.text}\n`, res)
    const claudeMd = join(root, 'CLAUDE.md')
    // A CLAUDE.md linked out of the repo is neither read (its text would land in the repo) nor written.
    const cur = repoPathInside(root, claudeMd) ? readText(claudeMd) : ''
    if (cur === undefined) writeIfChanged(root, 'CLAUDE.md', `${IMPORT_LINE}\n`, res)
    else if (!cur.split('\n').some((l) => l.trim() === IMPORT_LINE)) writeIfChanged(root, 'CLAUDE.md', cur + (cur.endsWith('\n') || !cur ? '' : '\n') + `\n${IMPORT_LINE}\n`, res)
    else res.unchanged++
  }
  return res
}

export const AGENTS_BEGIN = '<!-- context-gate:begin -->'
export const AGENTS_END = '<!-- context-gate:end -->'

/**
 * The sections for agent CLIs that read a Markdown instruction file (`AGENTS.md`, …) and have no plugin. Volatile
 * sections are left out: a file keeps a snapshot, and live state (branch, tickets) would be stale by the next turn.
 * The render goes between markers; text outside them is the user's and is kept. A file without markers gets them
 * appended.
 */
async function writeAgentsMd(ctx: Awaited<ReturnType<typeof buildContext>>, targets: string[], res: SyncResult): Promise<void> {
  const root = ctx.repo.root
  const system = ctx.prompts.system.map((cp) => ({ ...cp, sections: cp.sections.filter((sec) => sec.scope !== 'volatile') })).filter((cp) => cp.sections.length)
  const r = await renderWith({ ...ctx, prompts: { ...ctx.prompts, system } }, {})
  const block = `${AGENTS_BEGIN}\n<!-- ${MARK}: context-gate sync --agents-md (tier ${ctx.tier}${ctx.gate.profile ? `, профіль ${ctx.gate.profile}` : ''}); не редагуй між маркерами, джерело — ${ctx.repo.promptDir} -->\n\n${r.result.text.trim()}\n\n${AGENTS_END}`
  for (const raw of targets) {
    const rel = raw.replace(/^\.\//, '')
    const abs = join(root, rel)
    if (!rel || !repoPathInside(root, abs)) { res.diagnostics!.push(escapeDiag(rel || raw)); continue }
    writeIfChanged(root, rel, withAgentsBlock(readText(abs), block), res)
  }
}

/** `cur` with the generated block replaced (or appended when the file has none, or created). */
export function withAgentsBlock(cur: string | undefined, block: string): string {
  if (!cur) return `${block}\n`
  const b = cur.indexOf(AGENTS_BEGIN)
  const e = b < 0 ? -1 : cur.indexOf(AGENTS_END, b)
  if (b >= 0 && e >= 0) return cur.slice(0, b) + block + cur.slice(e + AGENTS_END.length)
  return cur + (cur.endsWith('\n') ? '' : '\n') + `\n${block}\n`
}

/** What `sync --watch` watches: every cursor-mdc and markdown-dir rule source (not only the root .cursor/rules). */
export function syncWatchPaths(root: string, promptDir: string): string[] {
  const config = loadRepo(root).config
  const dirs = new Set(['.cursor/rules', ...cursorRuleDirs(config).dirs])
  for (const src of ruleSourcesOf(config)) if (src.kind === 'markdown-dir' && src.dir) dirs.add(src.dir.replace(/^\.\//, '').replace(/\/+$/, ''))
  return [...dirs, promptDir, '.claude/gate.json'].map((p) => join(root, p)).filter((p) => existsSync(p) || existsSync(dirname(p)))
}

export function formatSync(res: SyncResult): string {
  const lines: string[] = []
  for (const w of res.written) lines.push(`записано ${posix(w)}`)
  for (const r of res.removed) lines.push(`видалено ${posix(r)}`)
  for (const d of res.diagnostics ?? []) lines.push(`${d.severity} ${d.code} ${d.message}${d.hint ? ` (${d.hint})` : ''}`)
  lines.push(`без змін: ${res.unchanged}; skillOverrides: ${Object.keys(res.overrides).length}`)
  return lines.join('\n') + '\n'
}

// ───────────────────────── SessionStart settings-hook (SPEC «Транспілятор») ─────────────────────────

/** Marks our hook entry in settings, so a re-install replaces it instead of adding a duplicate. */
export const SYNC_HOOK_MARK = 'sync --hook'
const SETTINGS_LOCAL = '.claude/settings.local.json'

interface HookCmd { type: 'command'; command: string; timeout?: number }
interface HookMatcherEntry { matcher?: string; hooks: HookCmd[] }

/** The command the hook runs: this CLI bundle when we run from it, else `npx context-gate`. */
export function syncHookCommand(cliPath: string | undefined = process.argv[1]): string {
  const q = (s: string) => (/^[\w@%+=:,./-]+$/.test(s) ? s : `'${s.replace(/'/g, `'\\''`)}'`)
  const bin = cliPath && /(^|[\\/])cli\.[cm]?js$/.test(cliPath) ? `node ${q(cliPath)}` : 'npx --no-install context-gate'
  return `${bin} ${SYNC_HOOK_MARK}`
}

const isOurHook = (m: HookMatcherEntry): boolean => Array.isArray(m?.hooks) && m.hooks.some((h) => typeof h?.command === 'string' && h.command.includes(SYNC_HOOK_MARK))

/** Settings with our SessionStart entry added (replacing a previous one) or, with `uninstall`, removed. Other hooks are kept. */
export function mergeSyncHook(settings: Record<string, unknown>, command: string, uninstall = false): Record<string, unknown> {
  const out = { ...settings }
  const hooks: Record<string, HookMatcherEntry[]> = { ...((settings.hooks && typeof settings.hooks === 'object' ? settings.hooks : {}) as Record<string, HookMatcherEntry[]>) }
  const kept = (Array.isArray(hooks.SessionStart) ? hooks.SessionStart : []).filter((m) => !isOurHook(m))
  if (!uninstall) kept.push({ hooks: [{ type: 'command', command, timeout: 60 }] })
  if (kept.length) hooks.SessionStart = kept
  else delete hooks.SessionStart
  if (Object.keys(hooks).length) out.hooks = hooks
  else delete out.hooks
  return out
}

/** `sync --install-hook` / `--uninstall-hook`: writes `.claude/settings.local.json`. */
export function installSyncHook(root: string, o: { uninstall?: boolean; command?: string } = {}): { path: string; changed: boolean; command: string; invalid?: boolean } {
  const abs = join(root, SETTINGS_LOCAL)
  const command = o.command ?? syncHookCommand()
  const cur = readSettingsForUpdate(abs)
  if (!cur) return { path: SETTINGS_LOCAL, changed: false, command, invalid: true }
  const next = mergeSyncHook(cur, command, o.uninstall)
  const changed = JSON.stringify(next) !== JSON.stringify(cur) || (!existsSync(abs) && !o.uninstall)
  if (changed) writeJson(abs, next, root)
  return { path: SETTINGS_LOCAL, changed, command }
}

/**
 * stdout of `sync --hook` for Claude Code's SessionStart: `reloadSkills: true` when the sync wrote or removed
 * skills (the generated `cursor-*` skills or SKILL.md), so the session sees them without a restart.
 */
export function syncHookOutput(res: SyncResult): string {
  const skills = [...res.written, ...res.removed].some((p) => p.startsWith('.claude/skills/'))
  return JSON.stringify(skills ? { hookSpecificOutput: { hookEventName: 'SessionStart', reloadSkills: true } } : {}) + '\n'
}

/** `sync --hook` (run from the SessionStart hook), `--install-hook`, `--uninstall-hook`. Never fails the hook. */
export async function syncHookMode(o: ContextOptions & { noPrompt?: boolean; noOverrides?: boolean; hard?: boolean }, mode: 'hook' | 'install' | 'uninstall'): Promise<{ code: number; out: string; err: string }> {
  if (mode !== 'hook') {
    const r = installSyncHook(o.root, { uninstall: mode === 'uninstall' })
    if (r.invalid) return { code: 1, out: '', err: `G301 ${r.path} не парситься як JSON-об'єкт — не змінюю його (виправ JSON і повтори)\n` }
    const what = mode === 'install' ? `SessionStart-хук «${r.command}» (reloadSkills)` : 'SessionStart-хук context-gate sync'
    return { code: 0, out: r.changed ? `${mode === 'install' ? 'додано' : 'прибрано'} ${what} у ${r.path}\n` : `${r.path}: без змін\n`, err: '' }
  }
  try {
    const res = await syncCommand(o)
    const err = (res.diagnostics ?? []).filter((d) => d.severity !== 'info').map((d) => `context-gate sync: ${d.code} ${d.message}${d.hint ? ` (${d.hint})` : ''}\n`).join('')
    return { code: 0, out: syncHookOutput(res), err }
  } catch (e) {
    return { code: 0, out: '{}\n', err: `context-gate sync: ${(e as Error).message}\n` }
  }
}
