// `context-gate sync`: the static harness adapter (SPEC «Режими запуску», сценарій 9). Without mods:
//   .mdc → .claude/rules/cursor/*.md (always/auto) + .claude/skills/cursor-<id>/SKILL.md (agent/manual)
//   profile/tier decision → skillOverrides in .claude/settings.local.json
//   DSL → one render into .claude/prompt.generated.md, imported from CLAUDE.md with `@.claude/prompt.generated.md`

import { existsSync, readdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { skillNameForRule, transpileAgentRule, transpileRuleToClaudeRule } from '../../core/src/mdc.ts'
import { skillOverridesFor } from '../../core/src/decide.ts'
import { buildContext, type ContextOptions } from './context.ts'
import { renderWith } from './cmd-run.ts'
import { posix, readJson, readText, walkFiles, writeJson, writeText } from './util.ts'

export const GENERATED_PROMPT = '.claude/prompt.generated.md'
export const IMPORT_LINE = '@.claude/prompt.generated.md'
const MARK = 'generated by context-gate'

export interface SyncResult { written: string[]; removed: string[]; unchanged: number; overrides: Record<string, string> }

function writeIfChanged(root: string, rel: string, text: string, res: SyncResult): void {
  const abs = join(root, rel)
  if (readText(abs) === text) { res.unchanged++; return }
  writeText(abs, text)
  res.written.push(rel)
}

export async function syncCommand(o: ContextOptions & { noPrompt?: boolean; noRules?: boolean; noOverrides?: boolean; hard?: boolean }): Promise<SyncResult> {
  const ctx = await buildContext({ ...o, dryScripts: o.dryScripts })
  const root = ctx.repo.root
  const res: SyncResult = { written: [], removed: [], unchanged: 0, overrides: {} }

  // ── rules ──
  if (!o.noRules) {
    const wantRules = new Set<string>()
    const wantSkills = new Set<string>()
    for (const r of ctx.rules) {
      const md = transpileRuleToClaudeRule(r)
      if (md !== undefined) {
        const rel = `.claude/rules/cursor/${r.id}.md`
        wantRules.add(rel)
        writeIfChanged(root, rel, md, res)
      } else {
        const name = skillNameForRule(r)
        const rel = `.claude/skills/${name}/SKILL.md`
        wantSkills.add(name)
        writeIfChanged(root, rel, transpileAgentRule(r), res)
      }
    }
    // Remove generated files whose rule disappeared.
    for (const f of existsSync(join(root, '.claude/rules/cursor')) ? walkFiles(root, { under: '.claude/rules/cursor' }) : []) {
      if (f.endsWith('.md') && !wantRules.has(f) && (readText(join(root, f)) ?? '').includes(MARK)) { rmSync(join(root, f)); res.removed.push(f) }
    }
    const skillsDir = join(root, '.claude/skills')
    if (existsSync(skillsDir)) {
      for (const d of readdirSync(skillsDir)) {
        if (!d.startsWith('cursor-') || wantSkills.has(d)) continue
        const p = join(skillsDir, d, 'SKILL.md')
        if ((readText(p) ?? '').includes(MARK)) { rmSync(join(skillsDir, d), { recursive: true, force: true }); res.removed.push(`.claude/skills/${d}/SKILL.md`) }
      }
    }
  }

  // ── skillOverrides for the chosen profile / tier ──
  if (!o.noOverrides) {
    const gate = ctx.gate
    const overrides: Record<string, string> = skillOverridesFor(gate, { hard: !!o.hard })
    res.overrides = overrides
    const settingsRel = '.claude/settings.local.json'
    const statePath = join(ctx.repo.cacheDir, 'sync-state.json')
    const state = readJson<{ overrides?: string[] }>(statePath) ?? {}
    const settings = readJson<Record<string, unknown>>(join(root, settingsRel)) ?? {}
    const cur = (settings.skillOverrides && typeof settings.skillOverrides === 'object' ? { ...(settings.skillOverrides as Record<string, string>) } : {})
    for (const k of state.overrides ?? []) delete cur[k]
    const next = { ...cur, ...overrides }
    const out = { ...settings }
    if (Object.keys(next).length) out.skillOverrides = Object.fromEntries(Object.entries(next).sort(([a], [b]) => a.localeCompare(b)))
    else delete out.skillOverrides
    if (JSON.stringify(out) !== JSON.stringify(settings) || !existsSync(join(root, settingsRel)) && Object.keys(next).length) {
      writeJson(join(root, settingsRel), out)
      res.written.push(settingsRel)
    } else res.unchanged++
    writeJson(statePath, { overrides: Object.keys(overrides) })
  }

  // ── DSL → one render + CLAUDE.md import ──
  if (!o.noPrompt && (ctx.prompts.system.length > 0)) {
    const r = await renderWith(ctx, {})
    const head = `<!-- ${MARK}: context-gate sync (tier ${ctx.tier}${ctx.gate.profile ? `, профіль ${ctx.gate.profile}` : ''}); не редагуй вручну, джерело — ${ctx.repo.promptDir} -->`
    writeIfChanged(root, GENERATED_PROMPT, `${head}\n\n${r.result.text}\n`, res)
    const claudeMd = join(root, 'CLAUDE.md')
    const cur = readText(claudeMd)
    if (cur === undefined) writeIfChanged(root, 'CLAUDE.md', `${IMPORT_LINE}\n`, res)
    else if (!cur.split('\n').some((l) => l.trim() === IMPORT_LINE)) writeIfChanged(root, 'CLAUDE.md', cur + (cur.endsWith('\n') || !cur ? '' : '\n') + `\n${IMPORT_LINE}\n`, res)
    else res.unchanged++
  }
  return res
}

export function syncWatchPaths(root: string, promptDir: string): string[] {
  return ['.cursor/rules', promptDir, '.claude/gate.json'].map((p) => join(root, p)).filter((p) => existsSync(p) || existsSync(dirname(p)))
}

export function formatSync(res: SyncResult): string {
  const lines: string[] = []
  for (const w of res.written) lines.push(`записано ${posix(w)}`)
  for (const r of res.removed) lines.push(`видалено ${posix(r)}`)
  lines.push(`без змін: ${res.unchanged}; skillOverrides: ${Object.keys(res.overrides).length}`)
  return lines.join('\n') + '\n'
}

// ───────────────────────── SessionStart settings-hook (SPEC «Транспілятор») ─────────────────────────

/** Marks our hook entry in settings, so a re-install replaces it instead of adding a duplicate. */
export const SYNC_HOOK_MARK = 'sync --hook'
const SETTINGS_LOCAL = '.claude/settings.local.json'

interface HookCmd { type: 'command'; command: string; timeout?: number }
interface HookMatcherEntry { matcher?: string; hooks: HookCmd[] }

/** The command the hook runs: this CLI bundle when we run from it, else `npx context-gate`. */
export function syncHookCommand(cliPath: string | undefined = process.argv[1]): string {
  const q = (s: string) => (/^[\w@%+=:,./-]+$/.test(s) ? s : `'${s.replace(/'/g, `'\\''`)}'`)
  const bin = cliPath && /(^|[\\/])cli\.[cm]?js$/.test(cliPath) ? `node ${q(cliPath)}` : 'npx --no-install context-gate'
  return `${bin} ${SYNC_HOOK_MARK}`
}

const isOurHook = (m: HookMatcherEntry): boolean => Array.isArray(m?.hooks) && m.hooks.some((h) => typeof h?.command === 'string' && h.command.includes(SYNC_HOOK_MARK))

/** Settings with our SessionStart entry added (replacing a previous one) or, with `uninstall`, removed. Other hooks are kept. */
export function mergeSyncHook(settings: Record<string, unknown>, command: string, uninstall = false): Record<string, unknown> {
  const out = { ...settings }
  const hooks: Record<string, HookMatcherEntry[]> = { ...((settings.hooks && typeof settings.hooks === 'object' ? settings.hooks : {}) as Record<string, HookMatcherEntry[]>) }
  const kept = (Array.isArray(hooks.SessionStart) ? hooks.SessionStart : []).filter((m) => !isOurHook(m))
  if (!uninstall) kept.push({ hooks: [{ type: 'command', command, timeout: 60 }] })
  if (kept.length) hooks.SessionStart = kept
  else delete hooks.SessionStart
  if (Object.keys(hooks).length) out.hooks = hooks
  else delete out.hooks
  return out
}

/** `sync --install-hook` / `--uninstall-hook`: writes `.claude/settings.local.json`. */
export function installSyncHook(root: string, o: { uninstall?: boolean; command?: string } = {}): { path: string; changed: boolean; command: string } {
  const abs = join(root, SETTINGS_LOCAL)
  const cur = readJson<Record<string, unknown>>(abs) ?? {}
  const command = o.command ?? syncHookCommand()
  const next = mergeSyncHook(cur, command, o.uninstall)
  const changed = JSON.stringify(next) !== JSON.stringify(cur) || (!existsSync(abs) && !o.uninstall)
  if (changed) writeJson(abs, next)
  return { path: SETTINGS_LOCAL, changed, command }
}

/**
 * stdout of `sync --hook` for Claude Code's SessionStart: `reloadSkills: true` when the sync wrote or removed
 * skills (the generated `cursor-*` skills or SKILL.md), so the session sees them without a restart.
 */
export function syncHookOutput(res: SyncResult): string {
  const skills = [...res.written, ...res.removed].some((p) => p.startsWith('.claude/skills/'))
  return JSON.stringify(skills ? { hookSpecificOutput: { hookEventName: 'SessionStart', reloadSkills: true } } : {}) + '\n'
}

/** `sync --hook` (run from the SessionStart hook), `--install-hook`, `--uninstall-hook`. Never fails the hook. */
export async function syncHookMode(o: ContextOptions & { noPrompt?: boolean; noOverrides?: boolean; hard?: boolean }, mode: 'hook' | 'install' | 'uninstall'): Promise<{ code: number; out: string; err: string }> {
  if (mode !== 'hook') {
    const r = installSyncHook(o.root, { uninstall: mode === 'uninstall' })
    const what = mode === 'install' ? `SessionStart-хук «${r.command}» (reloadSkills)` : 'SessionStart-хук context-gate sync'
    return { code: 0, out: r.changed ? `${mode === 'install' ? 'додано' : 'прибрано'} ${what} у ${r.path}\n` : `${r.path}: без змін\n`, err: '' }
  }
  try {
    return { code: 0, out: syncHookOutput(await syncCommand(o)), err: '' }
  } catch (e) {
    return { code: 0, out: '{}\n', err: `context-gate sync: ${(e as Error).message}\n` }
  }
}
