// Editor typings for a user repo without `@context-gate/jsx` in node_modules (the packages are not on npm):
// `<prompt dir>/tsconfig.json` (jsx react-jsx, jsxImportSource @context-gate/jsx, `paths` → `.types/jsx/…`)
// plus `.types/jsx/` — copies of the jsx package declarations shipped with the CLI (`dist/jsx-types/`,
// built by `npm run build:jsx-types`). Written by `init` and on every `build`, so tsserver resolves component
// names, props, `arg.*` and the `ctx` typing (`.types/ctx.d.ts`) with nothing installed.

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { posix } from './util.ts'

/** First line of a generated tsconfig: while it is there, `build` keeps the file current. */
export const TSCONFIG_MARK = '// Generated by context-gate (editor types for *.prompt.tsx). Remove this line to keep your own edits.'

/** `dist/jsx-types` next to the bundle (`dist/cli.js`) or of the repo (sources); undefined when not built. */
export function jsxTypesDir(): string | undefined {
  const here = dirname(fileURLToPath(import.meta.url))
  for (const c of [join(here, 'jsx-types'), join(here, '../../../dist/jsx-types')]) if (existsSync(join(c, 'jsx', 'src', 'index.d.ts'))) return resolve(c)
  return undefined
}

const JSX_ENTRY = '.types/jsx/jsx/src'

/** The generated `<prompt dir>/tsconfig.json` text (JSONC). */
export function promptTsconfig(): string {
  const json = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      jsx: 'react-jsx',
      jsxImportSource: '@context-gate/jsx',
      strict: true,
      noEmit: true,
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      skipLibCheck: true,
      paths: {
        '@context-gate/jsx': [`./${JSX_ENTRY}/index.d.ts`],
        '@context-gate/jsx/jsx-runtime': [`./${JSX_ENTRY}/jsx-runtime.d.ts`],
        '@context-gate/jsx/jsx-dev-runtime': [`./${JSX_ENTRY}/jsx-runtime.d.ts`],
        '@context-gate/jsx/compile': [`./${JSX_ENTRY}/compile.d.ts`],
      },
    },
    include: ['**/*.tsx', '**/*.ts', '.types/*.d.ts'],
    exclude: ['.compiled', '.trace', '.types/jsx'],
  }
  return TSCONFIG_MARK + '\n' + JSON.stringify(json, null, 2) + '\n'
}

function sameTree(a: string, b: string): boolean {
  let names: string[]
  try { names = readdirSync(a) } catch { return false }
  for (const n of names) {
    const pa = join(a, n)
    const pb = join(b, n)
    if (statSync(pa).isDirectory()) { if (!sameTree(pa, pb)) return false; continue }
    try { if (!readFileSync(pa).equals(readFileSync(pb))) return false } catch { return false }
  }
  return true
}

export interface EditorTypesResult { written: string[]; notes: string[] }

/**
 * Writes `<dir>/.types/jsx/` (when the shipped declarations differ) and `<dir>/tsconfig.json` (when absent or
 * still carrying {@link TSCONFIG_MARK}). Paths in `written` are repo-relative. Never throws.
 */
export function writeEditorTypes(root: string, dir = '.claude/prompt'): EditorTypesResult {
  const out: EditorTypesResult = { written: [], notes: [] }
  const promptDir = resolve(root, dir)
  const rel = (p: string) => posix(relative(root, p))
  try {
    const src = jsxTypesDir()
    const dest = join(promptDir, '.types', 'jsx')
    if (!src) out.notes.push('типи @context-gate/jsx не знайдено поруч із CLI (npm run build:jsx-types) — .types/jsx/ не оновлено')
    else if (!sameTree(src, dest)) {
      rmSync(dest, { recursive: true, force: true })
      mkdirSync(dest, { recursive: true })
      cpSync(src, dest, { recursive: true })
      out.written.push(rel(dest) + '/')
    }
    const tsconfig = join(promptDir, 'tsconfig.json')
    let cur: string | undefined
    try { cur = readFileSync(tsconfig, 'utf8') } catch { cur = undefined }
    const next = promptTsconfig()
    if (cur === undefined || (cur.startsWith(TSCONFIG_MARK) && cur !== next)) {
      mkdirSync(promptDir, { recursive: true })
      writeFileSync(tsconfig, next)
      out.written.push(rel(tsconfig))
    } else if (!cur.startsWith(TSCONFIG_MARK) && !cur.includes(JSX_ENTRY)) {
      out.notes.push(`${rel(tsconfig)} — власний файл: додай paths @context-gate/jsx → ./${JSX_ENTRY}/index.d.ts, щоб редактор бачив типи`)
    }
  } catch (e) {
    out.notes.push(`типи для редактора не записано: ${(e as Error).message}`)
  }
  return out
}
